version: '3'
services:
  db:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./docker:/docker-entrypoint-initdb.d/"
